"use client";

import Link from "next/link";
import { FileText, Sparkles } from "lucide-react";

import { EmptyState } from "@/components/EmptyState";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ROUTES } from "@/constants/routes";
import { useLatestSummary } from "@/features/summaries/api/queries";
import { formatPlantTime, formatShiftDate } from "@/lib/datetime";

/**
 * "Previous Shift Summary Report" — the fourth enabled widget in the prototype's
 * `dashWidgets` (`app-source.txt` 112), and §6.1's "review the previous
 * summary" at the start of a shift.
 *
 * It shows what the summary *is* and links to it; it does not restate the body,
 * which the three section cards beside it already cover.
 *
 * **FR-SUM-05** is why the AI-generated badge is not decoration: summaries
 * "support handover but do not replace the manual log-review meeting; summaries
 * are not formal records". Anyone reading this at 06:00 should be able to see
 * that at a glance.
 */
export const PreviousShiftSummaryCard = () => {
  const { data: summary, isLoading } = useLatestSummary();

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <FileText className="size-4 text-primary" aria-hidden />
          Previous shift summary
        </CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {isLoading ? (
          <div className="flex flex-col gap-3">
            <Skeleton className="h-5 w-3/4" />
            <Skeleton className="h-4 w-1/2" />
          </div>
        ) : !summary ? (
          <EmptyState
            icon={FileText}
            title="No summary yet"
            description="Nothing has been generated for a completed shift."
          />
        ) : (
          <>
            <div className="flex flex-col gap-1.5">
              <p className="text-sm font-medium">{summary.name}</p>
              <p className="text-xs text-muted-foreground">
                {summary.id} · {formatShiftDate(summary.shiftDate)} ·{" "}
                {summary.windowLabel}
              </p>
              <p className="text-xs text-muted-foreground">
                Generated by {summary.generatedBy.displayName} at{" "}
                {formatPlantTime(summary.generatedAt)}
              </p>
            </div>

            <Badge className="w-fit bg-accent text-accent-foreground">
              <Sparkles className="size-3" aria-hidden />
              AI-generated · not a formal record
            </Badge>

            <div className="flex flex-wrap gap-2">
              <Link
                href={ROUTES.SUMMARY_DETAIL(summary.id)}
                className={buttonVariants({ size: "sm" })}
              >
                Open summary
              </Link>
              <Link
                href={ROUTES.SUMMARIES}
                className={buttonVariants({ variant: "secondary", size: "sm" })}
              >
                All summaries
              </Link>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
};
