"use client";

import { useMemo } from "react";
import Link from "next/link";
import {
  createColumnHelper,
  getCoreRowModel,
  useReactTable,
} from "@tanstack/react-table";

import { DataTable } from "@/components/data-table/DataTable";
import { DataTablePagination } from "@/components/data-table/DataTablePagination";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { ROUTES } from "@/constants/routes";
import { useSummariesList } from "@/features/summaries/api/queries";
import { SummariesFilterBar } from "@/features/summaries/components/SummariesFilterBar";
import { useSummaryFilters } from "@/features/summaries/hooks/useSummaryFilters";
import type { SummaryListItem } from "@/features/summaries/schemas";
import { formatPlantTime, formatShiftDate } from "@/lib/datetime";

/**
 * The shift-summary list — prototype `summary()`, `app-source.txt` 1365–1390.
 *
 * Columns follow its header row (1380) exactly: Summary ID, Shift Name, Date,
 * Generated By, Role, Generated Time, Actions.
 *
 * Three translations worth naming:
 *
 * - The prototype makes the whole `<tr>` clickable (1381). A row handler is
 *   unreachable by keyboard and cannot be opened in a new tab, so the ID cell is
 *   a `<Link>` instead — the same correction `ActionsTable` made.
 * - Its subtitle reads "· 24 total" (1373) while the mock array holds 14. The
 *   count here comes from the response.
 * - `paged()`/`pager()` slice client-side (1381, 1389). This pages on the server
 *   with the page in the query key.
 *
 * The role cell is a plain `Badge`, not `StatusPill`: `generatedByRole` is a
 * display label, and `StatusPill`'s union is deliberately closed over the three
 * things that have a *lifecycle*. A summary has no status.
 */

const columnHelper = createColumnHelper<SummaryListItem>();

export const SummariesTable = () => {
  const { filters, queryFilters, setFilter, reset, isFiltered } =
    useSummaryFilters();

  const { data, isLoading, isFetching } = useSummariesList(queryFilters);

  const columns = useMemo(
    () => [
      columnHelper.accessor("id", {
        header: "Summary ID",
        cell: (info) => (
          <Link
            href={ROUTES.SUMMARY_DETAIL(info.getValue())}
            className="font-medium text-primary underline-offset-4 hover:underline"
          >
            {info.getValue()}
          </Link>
        ),
      }),
      columnHelper.accessor("name", { header: "Shift Name" }),
      columnHelper.accessor("shiftDate", {
        header: "Date",
        cell: (info) => formatShiftDate(info.getValue()),
      }),
      columnHelper.accessor("generatedBy.displayName", {
        id: "generatedBy",
        header: "Generated By",
      }),
      columnHelper.accessor("generatedByRole", {
        header: "Role",
        cell: (info) => <Badge variant="secondary">{info.getValue()}</Badge>,
      }),
      columnHelper.accessor("generatedAt", {
        header: "Generated Time",
        cell: (info) => formatPlantTime(info.getValue()),
      }),
      columnHelper.display({
        id: "actions",
        header: () => <span className="sr-only">Actions</span>,
        cell: ({ row }) => (
          <div className="flex justify-end">
            <Link
              href={ROUTES.SUMMARY_DETAIL(row.original.id)}
              aria-label={`View ${row.original.name}`}
              className={buttonVariants({ variant: "ghost", size: "sm" })}
            >
              View
            </Link>
          </div>
        ),
      }),
    ],
    []
  );

  const table = useReactTable({
    data: data?.items ?? [],
    columns,
    getCoreRowModel: getCoreRowModel(),
    // The server does the paging and the filtering; the table must not re-slice.
    manualPagination: true,
    manualFiltering: true,
    rowCount: data?.total ?? 0,
  });

  return (
    <div className="flex flex-col gap-4">
      <SummariesFilterBar
        filters={filters}
        isFiltered={isFiltered}
        onChange={setFilter}
        onReset={reset}
      />

      <DataTable
        table={table}
        isLoading={isLoading}
        caption="Shift summaries, with the shift, date, author and generation time"
        emptyMessage={
          isFiltered
            ? "No summaries match these filters."
            : "No shift summaries yet."
        }
      />

      <DataTablePagination
        page={filters.page}
        pageSize={filters.pageSize}
        total={data?.total ?? 0}
        disabled={isFetching}
        onPageChange={(page) => setFilter("page", page)}
        onPageSizeChange={(pageSize) => setFilter("pageSize", pageSize)}
      />
    </div>
  );
};
