import { screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { SummaryDetail } from "@/features/summaries/components/SummaryDetail";
import { renderWithProviders } from "@/test/utils";
import {
  envelope,
  installMockApi,
  mockRoute,
  resetMockApi,
} from "@/test/mockApi";

const ACTOR = {
  username: "said.albusaidi",
  display_name: "Said Al-Busaidi",
} as const;

const SUMMARY_ID = "SUM-20260731-D";

const summary = (overrides: Record<string, unknown> = {}) => ({
  id: SUMMARY_ID,
  shift_id: "20260731-D",
  name: "Day Shift – 31 Jul 2026",
  window_label: "Day (06:00–18:00)",
  shift_date: "20260731",
  generated_at: "2026-07-31T14:05:00+00:00",
  generated_by: ACTOR,
  generated_by_role: "Operator",
  generation: "end_of_shift",
  sections: [
    {
      kind: "activities",
      items: [
        {
          text: "Routine N2 purge completed on Unit 3",
          severity: "low",
          record_id: "ELB-20260731-0058",
        },
      ],
    },
    {
      kind: "critical_alarms",
      items: [
        {
          text: "B-train compressor trip at 02:14",
          severity: "critical",
          record_id: "ELB-20260731-0042",
        },
      ],
    },
  ],
  comments: [],
  ai_confirmations: [],
  ...overrides,
});

/**
 * The Administrator switches; `enabled` is what FR-SUM-08 turns on.
 *
 * The fixture carries `affects_role` because `workflowWireSchema` requires it.
 * An earlier version omitted it: the parse threw, `useIsWorkflowEnabled` fell
 * back to its fail-closed `false`, and the "composer hidden" tests all still
 * passed — for the wrong reason. The paired "composer shown" test is what
 * catches that, which is why both directions are asserted.
 */
const stubWorkflows = (commentingEnabled: boolean) => {
  mockRoute("GET", /\/admin\/workflows$/, () =>
    envelope({
      items: [
        {
          key: "operator_comment_permission",
          enabled: commentingEnabled,
          affects_role: "operator",
        },
      ],
    })
  );
};

const stubSummary = (overrides: Record<string, unknown> = {}) => {
  mockRoute("GET", /\/summaries\/[^/]+$/, () => envelope(summary(overrides)));
};

beforeEach(() => {
  installMockApi();
});

afterEach(() => {
  resetMockApi();
});

describe("SummaryDetail", () => {
  it("renders the summary through the real Zod boundary", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(
      await screen.findByRole("heading", { name: "Day Shift – 31 Jul 2026" })
    ).toBeVisible();
    expect(screen.getByText(/Generated by Said Al-Busaidi/)).toBeVisible();
  });

  /**
   * **FR-SUM-06** — "Attach source references (shift date, timestamp, record ID)
   * to each summary." The prototype hardcodes these (app-source.txt 1414–1417),
   * identical for every summary; here they come from the payload.
   */
  it("prints every item's source record id (FR-SUM-06)", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(await screen.findByText("ELB-20260731-0058")).toBeVisible();
    expect(screen.getByText("ELB-20260731-0042")).toBeVisible();
  });

  /** FR-SUM-01's four sections, rendered by name rather than by colour. */
  it("labels each section and each item's severity in words", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(
      await screen.findByRole("heading", { name: /Activities/ })
    ).toBeVisible();
    expect(
      screen.getByRole("heading", { name: /Critical alarms/ })
    ).toBeVisible();
    // WCAG 1.4.1: severity is a word, not only a hue.
    expect(screen.getByText("Critical")).toBeVisible();
    expect(screen.getByText("Low")).toBeVisible();
  });

  it("shows a not-found screen rather than an empty page", async () => {
    mockRoute("GET", /\/summaries\/[^/]+$/, () => envelope(null), 404);
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId="SUM-nope" />);

    expect(await screen.findByText("Summary not found")).toBeVisible();
    expect(
      screen.getByRole("link", { name: /Back to shift summaries/ })
    ).toBeVisible();
  });

  /* ---- FR-SUM-08: comment access is Admin/Super-User controlled ---------- */

  /**
   * The Operator fixture holds `summary:read` but **not** `summary:comment`, so
   * with the workflow off the composer must not appear. This is the exact
   * predicate `summaries/[id]/comments/route.ts` enforces.
   */
  it("hides the composer when neither the permission nor the toggle allows it", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(
      await screen.findByText(/Commenting is turned off by your administrator/)
    ).toBeVisible();
    expect(screen.queryByLabelText("Add a comment")).not.toBeInTheDocument();
  });

  it("shows the composer once the Administrator enables the workflow", async () => {
    stubSummary();
    stubWorkflows(true);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(await screen.findByLabelText("Add a comment")).toBeVisible();
    expect(
      screen.queryByText(/Commenting is turned off by your administrator/)
    ).not.toBeInTheDocument();
  });

  /**
   * A Supervisor holds `summary:comment` outright, so the toggle is irrelevant
   * to them — the predicate is an OR, not an AND. The prototype's role-name
   * check (`role === 'operator' && !opComment`, 1426) gets this wrong for anyone
   * holding two roles.
   */
  it("shows the composer for a permission holder even with the toggle off", async () => {
    installMockApi({
      username: "fatma.alhinai",
      displayName: "Fatma Al-Hinai",
      roles: ["supervisor"],
      permissions: ["shift:read", "summary:read", "summary:comment"],
    });
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(await screen.findByLabelText("Add a comment")).toBeVisible();
  });

  /**
   * Fails closed while the workflow answer is in flight, matching
   * `useIsWorkflowEnabled`'s own posture — a composer that flickers into
   * existence invites a click that then 403s.
   */
  it("does not offer the composer before the workflow answer arrives", async () => {
    stubSummary();
    mockRoute("GET", /\/admin\/workflows$/, () => envelope(null), 500);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    await screen.findByRole("heading", { name: "Day Shift – 31 Jul 2026" });
    expect(screen.queryByLabelText("Add a comment")).not.toBeInTheDocument();
  });

  /* ---- FR-SUM-09: export is [BACKEND] ----------------------------------- */

  /**
   * The requirement stays visible; the capability does not pretend. The
   * prototype toasts "exported as PDF" for a file it never produced
   * (app-source.txt 1407).
   */
  it("offers all three export formats and enables none of them", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(
      await screen.findByRole("button", { name: /Export/ })
    ).toBeInTheDocument();
  });

  /* ---- FR-PA-02 confirmations ------------------------------------------- */

  it("hides the AI confirmations card when there are none", async () => {
    stubSummary();
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    await screen.findByRole("heading", { name: "Day Shift – 31 Jul 2026" });
    expect(
      screen.queryByText("AI action confirmations")
    ).not.toBeInTheDocument();
  });

  it("lists AI confirmations with who confirmed them", async () => {
    stubSummary({
      ai_confirmations: [
        {
          id: "CONF-1",
          suggestion_id: "AI-118",
          title: "Inspect relief valve XV-118",
          confirmed_by: ACTOR,
          confirmed_at: "2026-07-31T10:30:00+00:00",
          comment: "Coordinate with maintenance before isolation.",
        },
      ],
    });
    stubWorkflows(false);

    renderWithProviders(<SummaryDetail summaryId={SUMMARY_ID} />);

    expect(
      await screen.findByText("Inspect relief valve XV-118")
    ).toBeVisible();
    expect(screen.getByText(/Confirmed by Said Al-Busaidi/)).toBeVisible();
  });
});
