"use client";

import Link from "next/link";
import {
  ArrowLeft,
  CircleCheck,
  FileText,
  MessagesSquare,
  SearchX,
  Sparkles,
} from "lucide-react";

import { DetailField } from "@/components/DetailField";
import { EmptyState } from "@/components/EmptyState";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { ROUTES } from "@/constants/routes";
import { useIsWorkflowEnabled } from "@/features/admin/api/queries";
import { useSummary } from "@/features/summaries/api/queries";
import { SummaryComments } from "@/features/summaries/components/SummaryComments";
import { SummaryExportMenu } from "@/features/summaries/components/SummaryExportMenu";
import { SummarySections } from "@/features/summaries/components/SummarySections";
import {
  formatPlantDateTime,
  formatPlantTime,
  formatShiftDate,
} from "@/lib/datetime";

/**
 * One shift summary — prototype `summaryDetail()`, `app-source.txt` 1392–1434.
 *
 * The prototype's layout ports closely: header with an export control, a wide
 * body column beside a details card, then comments, then AI confirmations. What
 * changes is where the content comes from — see `SummarySections`.
 *
 * Two prototype behaviours deliberately not carried over:
 *
 * - **Master/detail through `state.selSummary`** (1367). The list and the detail
 *   share one route there, so a summary has no address: it cannot be linked,
 *   bookmarked, or reached with the back button. Two routes here.
 * - **A working Export** (1403–1407). See `SummaryExportMenu` — there is no
 *   export endpoint, and the prototype's success toast describes a file that was
 *   never produced.
 *
 * **FR-SUM-05** is why nothing on this screen claims authority: summaries
 * "support handover but do not replace the manual log-review meeting; summaries
 * are not formal records". The AI-generated badge below says so on every one.
 */

interface SummaryDetailProps {
  summaryId: string;
}

export const SummaryDetail = ({ summaryId }: SummaryDetailProps) => {
  const { data: summary, isLoading, isError } = useSummary(summaryId);
  const commentingEnabled = useIsWorkflowEnabled("operator_comment_permission");

  if (isLoading) {
    return (
      <div className="flex flex-col gap-4">
        <Skeleton className="h-8 w-2/3" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (isError || !summary) {
    return (
      <EmptyState
        icon={SearchX}
        title="Summary not found"
        description="It may have been removed, or the id in the address bar is wrong."
        action={
          <Link href={ROUTES.SUMMARIES} className={buttonVariants()}>
            <ArrowLeft aria-hidden />
            Back to shift summaries
          </Link>
        }
      />
    );
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex flex-col gap-1.5">
          <h1 className="text-xl font-semibold tracking-tight">
            {summary.name}
          </h1>
          <p className="text-sm text-muted-foreground">
            {summary.id} · Generated by {summary.generatedBy.displayName} ·{" "}
            {summary.generatedByRole}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <SummaryExportMenu summaryId={summary.id} />
          <Link
            href={ROUTES.SUMMARIES}
            className={buttonVariants({ variant: "secondary" })}
          >
            {/* Mirrors with `dir`: "back" points the other way in Arabic. */}
            <ArrowLeft className="rtl:-scale-x-100" aria-hidden />
            Back to list
          </Link>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem] lg:items-start">
        <Card>
          <CardHeader>
            <CardTitle className="flex flex-wrap items-center gap-2 text-base">
              <Badge className="bg-accent text-accent-foreground">
                <Sparkles className="size-3" aria-hidden />
                AI-generated
              </Badge>
              <span className="text-sm font-normal text-muted-foreground">
                {formatShiftDate(summary.shiftDate)} · {summary.windowLabel} ·{" "}
                {summary.generatedBy.displayName}
              </span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <SummarySections sections={summary.sections} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <FileText className="size-4 text-primary" aria-hidden />
              Summary details
            </CardTitle>
          </CardHeader>
          <CardContent>
            <dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1">
              <DetailField label="Summary ID">
                <span className="font-semibold text-accent-foreground">
                  {summary.id}
                </span>
              </DetailField>
              <DetailField label="Shift">{summary.windowLabel}</DetailField>
              <DetailField label="Date">
                {formatShiftDate(summary.shiftDate)}
              </DetailField>
              <DetailField label="Generated by">
                {summary.generatedBy.displayName}
              </DetailField>
              <DetailField label="Role">
                <Badge variant="secondary">{summary.generatedByRole}</Badge>
              </DetailField>
              <DetailField label="Generated">
                <span className="tabular-nums">
                  {formatPlantTime(summary.generatedAt)}
                </span>
              </DetailField>
              <DetailField label="Generation">
                {/* FR-SUM-02: "both on demand and automatically at end of every shift". */}
                {summary.generation === "on_demand"
                  ? "On demand"
                  : "End of shift"}
              </DetailField>
            </dl>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <MessagesSquare className="size-4 text-primary" aria-hidden />
            Comments
          </CardTitle>
        </CardHeader>
        <CardContent>
          <SummaryComments
            summaryId={summary.id}
            comments={summary.comments}
            commentingEnabled={commentingEnabled}
          />
        </CardContent>
      </Card>

      {/*
        FR-PA-02's outcome, and §6.2(a) is why it is a record rather than a task
        list: confirming an AI-suggested action "adds it to the summary as a
        comment", with no assignee and no due date. The card is hidden entirely
        when empty — an empty "AI action confirmations" heading reads as though
        something failed to load.
      */}
      {summary.aiConfirmations.length > 0 ? (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <CircleCheck className="size-4 text-primary" aria-hidden />
              AI action confirmations
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="flex flex-col gap-4">
              {summary.aiConfirmations.map((confirmation) => (
                <li key={confirmation.id} className="flex flex-col gap-1">
                  <p className="text-sm font-medium">{confirmation.title}</p>
                  <p className="text-xs text-muted-foreground">
                    Confirmed by {confirmation.confirmedBy.displayName} ·{" "}
                    {formatPlantDateTime(confirmation.confirmedAt)}
                  </p>
                  {confirmation.comment ? (
                    <p className="text-sm text-muted-foreground">
                      {confirmation.comment}
                    </p>
                  ) : null}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
};
